server:
  port: 8050
spring:
  application:
    name: starrysea-file
ss: 
  fileroot: D:/develop/nginx-1.12.1/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    prefer-ip-address: true